server:
  port: 8083

spring:
  application:
    name: card-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

info:
  app:
    name: card-service
    version: 1.0.0
